### PR TITLE
Add a builder-style methods for creating Models and setting Note options

### PR DESCRIPTION
**Pull request by eholk**
I found this approach more readable when I want to set more than just the default options but not all of the options.

### CODE REVIEW

**Comment by yannickfunk** [comment]
Hey thanks again for proposing those changes, I'd appreciate having a way to build the model more conveniently. Currently, I am using the Builder pattern for some structs (i.e the [Template struct](https://docs.rs/genanki-rs/0.2.0/genanki_rs/struct.Template.html) ). Could we try to align those slightly different builder apis? Then we would have a uniform way across the available structs. What do you think?

**Comment by eholk** [comment]
Yeah, that sounds good to me!

So just to make sure I understand, being aligned with the `Template` struct means we'd be able to use the `Model` builder like this?
```rust
let model: Model = Model::new(1234, "my model").css("body { font-size: huge; }");
```
In other words, don't have a separate build step, but the field setters always consume the old `Model` and return a new one with the new property set?

**Comment by yannickfunk** [comment]
Looks good to me! Could you adapt the examples in the README accordingly? So that the new_with_options call is replaced by the build chain.

**Comment by eholk** [comment]
Sure, I'll try and update that this weekend.

Should we also mark the *_with_options methods as deprecated?

**Comment by eholk** [comment]
Okay, I just pushed a couple of commits that update the documentation. I made it so you can run many of the examples in libs.rs as doctests as well.

**Comment by yannickfunk** [comment]
Looks good, imho new_with_options and the builder can coexist, but if you want I am also fine with deprecating it. I'll approve, as soon as you say its merge ready, let's merge

**Review by yannickfunk — APPROVED** [review]

**Comment by eholk** [comment]
Sounds good, I don't mind keeping the old methods around either. Let's merge!

**Pull request merged**
